<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = 'Agenda de Contatos';
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap-typeahead.min.js'))              
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/scripts.js'))                
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
            <div class="container">
                <div class="header">
                    <ul class="nav nav-pills pull-right">
                        <?php
                            $url_contatos = $this->url('contatos');
                            $url_sobre = $this->url('sobre');
                        ?>
                        <li <?php echo $this->menuAtivo($url_contatos); ?>><a href="<?php echo $url_contatos; ?>">Início</a></li>
                        <li <?php echo $this->menuAtivo($url_sobre); ?>><a href="<?php echo $url_sobre; ?>">Sobre</a></li>
                    </ul>
                    <h3 class="text-muted"><?php echo $NAME_APPLICATION; ?></h3>
                </div>
            <!--</div>-->
        <?php echo $this->message(); ?>
            
            <div class="row marketing">
                <?php echo $this->content; ?>
            </div>           
            
        <!--<div class="container">-->
            <?php // echo $this->content; ?>
            <!--<hr>-->
            <div class="footer">
                <p class="muted credit pull-left">Company <a href="">© 2015</a></p>
                <p class="muted credit pull-right">Desenvolvido por Josué Jr.</p>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
